let A401 = ["BHOOVESH", "HARSH", "AYUSH", "PINKI"];
let B213 = ["ANIKET", "HARSHIT", "PRIYANSHU", "SHREYAS"];

// A401.push(B213);JAB AAP A401 MEIN B213 KO PUSH DIRECT PUSH KARTE HO TO B213 PURA KA PURA ARRAY AS A SINGLE ELEMENT PUSH HOJATA HAI  A401 MEIN

// console.log(A401); // Output: ["BHOOVESH", "HARSH", "AYUSH", "PINKI", ["ANIKET", "HARSHIT", "PRIYANSHU", "SHREYAS"]]
// console.log(A401[4]);
// console.log("CHINNAR => ", A401[4][3]);

//  INSTEAD OF PUSH B213 AS A SINGLE ELEMENT, WE CAN CONCATENATE THE TWO ARRAYS USING THE CONCAT METHOD

// A401 = A401.concat(B213);// A401.CONCAT(B213) RETURN A NEW ARRAY WHICH IS THE COMBINATION OF A401 AND B21k3
// console.log(A401);

// WE WILL USUALLY USE SPREAD OPERATOR TO CONCATENATE TWO ARRAYS
// A401 = [...A401,...B213]//SAME KAM KREAG AS CONCAT BAS ISME AAP 2 YA DO SE JYADA ARRAYS KO CONCATENATE KAR SAKTE HO BUT IN CONCAT YOU CAN ONLY CONCATENATE TWO ARRAYS AT A TIME
// console.log(A401);

// let newArray = [1, 2, 3, [4, 5, 6], 7, 7, 9, [10, 11, 12, [13, 14, 155]]];
// AB AGR ESE ARRAY MEIN AAPKO SIRF 1D ARRAY CHAHIYE TO AAP FLAT METHOD USE KAR SAKTE HO
// console.log(newArray.flat(Infinity));//ISME APKO DEPTH AS A PARAMETER DENAPDHTA HAI MTLB KI KITNE DEPTH TK ARRAYS KO MERGE KRNA HAI AGR SARE KO KRNA TO DO WRITE TEHRE INFINITY

// "isArray" IS A METHOD THAT CHECKS WHETHER THE GIVEN VALUE IS AN ARRAY OR NOT
// console.log(Array.isArray("BHOOVVI"));
// console.log(Array.isArray(A401));

// "FROM" METHOD CONVERTS THE GIVEN VALUE INTO AN ARRAY OR AN ARRAY LIKE OBJECT
// console.log(Array.from("BHOOVESH"));
// console.log(Array.from({ length: 7 }, (_, i) => i + 1));

// "OF" METHOD IS THE METHOD WHICH MAKES THE ARRAY OF THE GIVEN VALUES
// console.log(Array.of(1, 2, 4, 5));
